version: '3.9'
services:
  dtrack-ssc-bridge:
    build: ./docker/Dockerfile
    image: appsec/dtrack-ssc-bridge:0.1
    container_name: dtrack-ssc-bridge
    ports:
      - "8080:8080"
    environment:
      SSC_URL: https://ssc.example.com
      SSC_TOKEN: your_ssc_token
      DTRACK_URL: https://dtrack.example.com
      DTRACK_TOKEN: your_dtrack_token
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request, sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8080/healthz').status == 200 else sys.exit(1)"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"
  nginx:
    image: nginx:alpine
    container_name: dtrack-ssc-nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ssc-dtrack-bridge
